security:
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      security: false

  access_control: []

when@test:
  security:
    password_hashers: []
    providers: []
