twig:
    file_name_pattern: '*.twig'
    globals:
        app_name: '%app_name%'
        mapbox_token: '%env(MAPBOX_TOKEN)%'
        admin_email: '%env(ADMIN_EMAIL)%'

when@test:
    twig:
        strict_variables: true
