networks:
  street-guard_network:

volumes:
  mysql-data:

services:
  street-guard_app:
    container_name: street-guard_app
    build:
      context: .
      dockerfile: ./infrastructure/php/Dockerfile
    networks:
      - street-guard_network
    volumes:
      - .:/var/task
      - ./var:/var/task/var        # force create ./var
      - ./vendor:/var/task/vendor  # force create ./vendor
    depends_on:
      - mysql

  nginx:
    image: nginx:1.23.4-alpine
    ports:
      - "8000:80"
    volumes:
      - .:/var/task
      - ./infrastructure/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - street-guard_app
    networks:
      - street-guard_network

  mysql:
    image: bitnami/mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - type: volume
        source: mysql-data
        target: /bitnami/mysql/data
    networks:
      - street-guard_network

  phpmyadmin:
    image: bitnami/phpmyadmin:latest
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    depends_on:
      - mysql
    networks:
      - street-guard_network
